// Frontend/React/movie-app/src/pages/Auth/Register.tsx
import "../../styles/page.css";
import "../../styles/auth.css";
import { useState } from "react";
import { useNavigate, Link } from "react-router-dom";
import * as authApi from "../../services/auth/authApi";

const Register = () => {
  const [username, setUsername] = useState("");
  const [password, setPassword] = useState("");
  const [error, setError] = useState("");
  const [success, setSuccess] = useState("");
  const navigate = useNavigate();

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setError("");
    setSuccess("");
    try {
      await authApi.register({ username, password });
      setSuccess("Rejestracja udana! Możesz się zalogować.");
      setTimeout(() => navigate("/login"), 1200);
    } catch (err: any) {
      let msg = err?.response?.data?.message || "Błąd rejestracji";
      if (msg.toLowerCase().includes("forbidden")) {
        msg = "Nie masz uprawnień do rejestracji.";
      } else if (msg.toLowerCase().includes("conflict")) {
        msg = "Użytkownik o tej nazwie już istnieje.";
      } else if (msg.toLowerCase().includes("network")) {
        msg = "Brak połączenia z serwerem.";
      }
      setError(msg);
    }
  };

  return (
    <div className="auth-page">
      <div className="auth-box">
        <h2>Rejestracja</h2>
        <form onSubmit={handleSubmit}>
          <input
            type="text"
            placeholder="Nazwa użytkownika"
            value={username}
            onChange={e => setUsername(e.target.value)}
            required
            autoFocus
          />
          <input
            type="password"
            placeholder="Hasło"
            value={password}
            onChange={e => setPassword(e.target.value)}
            required
          />
          <button type="submit">Zarejestruj</button>
          {error && <div className="error">{error}</div>}
          {success && <div className="success">{success}</div>}
        </form>
        <div className="switch-link">
          Masz już konto? <Link to="/login">Zaloguj się</Link>
        </div>
      </div>
    </div>
  );
};

export default Register;

// Frontend/Angular/src/app/pages/auth/register/register.ts

import { Component } from '@angular/core';
import { Router } from '@angular/router';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { AuthApiService } from '../../../services/auth/auth-api.service';
import { RouterModule } from '@angular/router';

@Component({
  selector: 'app-register',
  templateUrl: './register.html',
  styleUrl: './register.scss',
  standalone: true,
  imports: [CommonModule, FormsModule, RouterModule],
})
export class Register {
  username = '';
  password = '';
  error = '';
  success = '';

  constructor(private authApi: AuthApiService, private router: Router) {}

      onSubmit() {
    this.error = '';
    this.success = '';

    this.authApi.register({
      username: this.username,
      password: this.password
    }).subscribe({
      next: (res: any) => {
        console.log("REGISTER RESPONSE:", res);

        this.success = 'Rejestracja udana! Możesz się zalogować.';

        setTimeout(() => this.router.navigate(['/login']), 1200);
      },

      error: (err) => {
        let msg = err?.error;

        if (typeof msg !== 'string') {
          msg = msg?.message || 'Błąd rejestracji';
        }

        if (typeof msg === 'string') {
          if (msg.toLowerCase().includes('forbidden')) {
            msg = 'Nie masz uprawnień do rejestracji.';
          } else if (
            msg.toLowerCase().includes('conflict') ||
            msg.toLowerCase().includes('exists')
          ) {
            msg = 'Użytkownik o tej nazwie już istnieje.';
          }
        }

        this.error = msg;
      }
    });
  }
}
