// Frontend/Angular/src/app/pages/movie/movie-details/movie-page-component/movie-page.component.ts
import {
  Component,
  OnInit,
  ChangeDetectionStrategy,
  ChangeDetectorRef
} from '@angular/core';

import { CommonModule } from '@angular/common';
import { ActivatedRoute, RouterModule } from '@angular/router';
import { Movie } from '../../../../services/movie/movie-types';
import { MovieApiService } from '../../../../services/movie/movie-api.service';
import { ReviewFormComponent } from './review-form.component';

@Component({
  selector: 'app-movie-page',
  standalone: true,
  imports: [CommonModule, RouterModule, ReviewFormComponent],
  templateUrl: './movie-page.component.html',
  styleUrls: ['./movie-page.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class MoviePageComponent implements OnInit {

  movie: Movie | null = null;
  loading = true;
  error = '';

  constructor(
    private route: ActivatedRoute,
    private api: MovieApiService,
    private cdr: ChangeDetectorRef
  ) {}

  ngOnInit(): void {
    this.loadMovie();
  }

  loadMovie(): void {
    const id = Number(this.route.snapshot.paramMap.get('id'));

    if (!id) {
      this.error = 'Brak ID filmu';
      this.loading = false;
      this.cdr.markForCheck();
      return;
    }

    this.loading = true;
    this.error = '';

    this.api.getMovieById(id).subscribe({
      next: (data) => {
        this.movie = data;
        this.loading = false;
        this.cdr.markForCheck();
      },
      error: () => {
        this.error = 'Nie udało się pobrać filmu';
        this.loading = false;
        this.cdr.markForCheck();
      }
    });
  }
}
<div class="movie-page" *ngIf="!loading && movie; else state">

  <div class="movie-hero">

    <img
      class="movie-poster"
      [src]="'http://localhost:8080' + movie.posterUrl"
      [alt]="movie.title"
    />

    <div class="movie-details">
      <h1>{{ movie.title }}</h1>

      <div class="badges">
        <span>⭐ {{ movie.averageRating || '—' }}</span>

        <span>
          {{ movie.durationMinutes ? movie.durationMinutes + ' min' : '—' }}
        </span>

        <span>
          {{ movie.releaseDate ? (movie.releaseDate | date:'yyyy') : '—' }}
        </span>
      </div>

      <p>{{ movie.description || '—' }}</p>
    </div>
  </div>

  <div class="movie-info">
    <p><b>Genres:</b> {{ movie.genres?.join(', ') || '—' }}</p>
    <p><b>Actors:</b> {{ movie.actors?.join(', ') || '—' }}</p>
    <p><b>Directors:</b> {{ movie.directors?.join(', ') || '—' }}</p>
  </div>

  <div class="review-form-wrapper">
    <h2>Recenzje</h2>

    <app-review-form
      [movieId]="movie.id"
      (reviewAdded)="loadMovie()"
    ></app-review-form>

      <div class="reviews">

    <div *ngIf="movie.reviews?.length; else noReviews">
      <div class="review" *ngFor="let r of movie.reviews">

        <div class="review-user">
          👤 {{ r.username || 'Anonim' }}
        </div>

        <div class="review-content">
          {{ r.content }}
        </div>

        <div class="review-date">
          {{ r.createdAt | date:'short' }}
        </div>

      </div>
    </div>

    <ng-template #noReviews>
      <p>Brak recenzji</p>
    </ng-template>

  </div>
  </div>

</div>

<ng-template #state>
  <div class="state">
    {{ loading ? 'Ładowanie...' : error }}
  </div>
</ng-template>

// Frontend/React/movie-app/src/pages/Movie/MoviePage.tsx
import { useEffect, useState, useCallback } from "react";
import { useParams } from "react-router-dom";
import { getMovieById } from "../../services/movie/movieApi";
import ReviewForm from "./components/ReviewForm";
import type { Movie } from "../../services/movie/movieTypes";
import "./movie-page.css";

const MoviePage = () => {
  const { id } = useParams<{ id: string }>();

  const [movie, setMovie] = useState<Movie | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");

  const fetchMovie = useCallback(async () => {
    if (!id) return;

    try {
      setLoading(true);
      setError("");

      const res = await getMovieById(Number(id));
      setMovie(res.data);
    } catch (e) {
      console.log("GET MOVIE ERROR:", e);
      setError("Nie udało się pobrać filmu");
    } finally {
      setLoading(false);
    }
  }, [id]);

  useEffect(() => {
    fetchMovie();
  }, [fetchMovie]);

  if (!id || loading || error || !movie) {
    return (
      <div className="movie-state">
        {error || (loading ? "Ładowanie..." : "Brak filmu")}
      </div>
    );
  }

  return (
    <div className="movie-page">

      <div className="movie-hero">

        <img
          src={`http://localhost:8080${movie.posterUrl}`}
          alt={movie.title}
          className="movie-poster"
        />

        <div className="movie-details">

          <h1 className="movie-title">{movie.title}</h1>

          <div className="movie-badges">
            <span className="badge">⭐ {movie.averageRating ?? "—"}</span>
            <span className="badge">
              {movie.durationMinutes ? `${movie.durationMinutes} min` : "—"}
            </span>
            <span className="badge">
              {movie.releaseDate
                ? new Date(movie.releaseDate).getFullYear()
                : "—"}
            </span>
          </div>

          <p className="movie-description">
            {movie.description || "Brak opisu filmu"}
          </p>

        </div>
      </div>

      <div className="movie-info-box">
        <div className="info-row">
          <span className="label">Gatunki</span>
          <span className="value">
            {movie.genres?.length ? movie.genres.join(", ") : "brak danych"}
          </span>
        </div>

        <div className="info-row">
          <span className="label">Aktorzy</span>
          <span className="value">
            {movie.actors?.length ? movie.actors.join(", ") : "brak danych"}
          </span>
        </div>

        <div className="info-row">
          <span className="label">Reżyserzy</span>
          <span className="value">
            {movie.directors?.length ? movie.directors.join(", ") : "brak danych"}
          </span>
        </div>

      </div>

      <div className="movie-reviews">
        <h2>Recenzje</h2>

        <ReviewForm
          movieId={movie.id}
          onReviewAdded={fetchMovie}
        />

        <div className="reviews-list">

          {movie.reviews?.length ? (
            movie.reviews.map((r: any) => (
              <div key={r.id} className="review-item">

                <div className="review-user">
                  👤 {r.user?.username ?? "unknown"}
                </div>

                <div className="review-content">
                  {r.content}
                </div>

                <div className="review-date">
                  {r.createdAt
                    ? new Date(r.createdAt).toLocaleDateString()
                    : ""}
                </div>

              </div>
            ))
          ) : (
            <p>Brak recenzji</p>
          )}

        </div>

      </div>

    </div>
  );
};

export default MoviePage;
