// Frontend/Angular/src/app/pages/movie/movie-details/movie-details.ts
import { CommonModule } from '@angular/common';
import { ChangeDetectorRef, Component, inject } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import { MovieApiService } from '../../../services/movie/movie-api.service';
import { catchError, finalize, of } from 'rxjs';

@Component({
  selector: 'app-movie-details',
  imports: [CommonModule],
  templateUrl: './movie-details.html',
  styleUrl: './movie-details.scss',
})
export class MovieDetails {
  private readonly route = inject(ActivatedRoute);
  private readonly movieApi = inject(MovieApiService);
  private readonly cdr = inject(ChangeDetectorRef);

  protected readonly movieId = this.route.snapshot.paramMap.get('id');
  protected readonly limits = [10, 100, 1000, 2500, 5000, 10000];
  protected logs: string[] = ['Gotowe'];
  protected loadingLimit: number | null = null;
  private addLog(message: string): void {
    this.logs = [...this.logs, message];
  }

  protected fetchMovies(limit: number): void {
    this.loadingLimit = limit;
    this.addLog(`Pobieranie ${limit} filmów...`);
    this.cdr.markForCheck();

    const start = performance.now();
    this.movieApi
      .getFirstMovies(limit)
      .pipe(
        catchError(() => {
          const durationMs = performance.now() - start;
          const durationSec = durationMs / 1000;
          this.addLog(
            `Pobieranie nie powiodło się po ${durationMs.toFixed(0)} ms (${durationSec.toFixed(2)} s).`
          );
          this.cdr.markForCheck();
          return of([]);
        }),
        finalize(() => {
          this.loadingLimit = null;
          this.cdr.markForCheck();
        })
      )
      .subscribe((movies) => {
        const durationMs = performance.now() - start;
        const count = Array.isArray(movies) ? movies.length : 0;
        const durationSec = durationMs / 1000;
        this.addLog(
          `Pobrano ${count} filmów w ${durationMs.toFixed(0)} ms (${durationSec.toFixed(2)} s).`
        );
        this.cdr.markForCheck();
      });
  }
}

// Frontend/React/movie-app/src/pages/Movie/MovieDetails.tsx
import { useState } from "react";
import "../../styles/page.css";
import { getFirstMovies } from "../../services/movie/movieApi";

const LIMITS = [10, 100, 1000, 2500, 5000, 10000];

const MovieDetails = () => {
  const [logs, setLogs] = useState<string[]>(["Gotowe"]);
  const [loadingLimit, setLoadingLimit] = useState<number | null>(null);
  const addLog = (message: string) => setLogs((prev) => [...prev, message]);

  const fetchMovies = async (limit: number) => {
    setLoadingLimit(limit);
    addLog(`Pobieranie ${limit} filmów...`);

    const start = performance.now();
    try {
      const response = await getFirstMovies(limit);
      const durationMs = performance.now() - start;
      const durationSec = durationMs / 1000;
      addLog(
        `Pobrano ${response.data.length} filmów w ${durationMs.toFixed(0)} ms (${durationSec.toFixed(2)} s, status ${response.status}).`
      );
    // eslint-disable-next-line @typescript-eslint/no-unused-vars
    } catch (error) {
      const durationMs = performance.now() - start;
      const durationSec = durationMs / 1000;
      addLog(`Pobieranie nie powiodło się po ${durationMs.toFixed(0)} ms (${durationSec.toFixed(2)} s).`);
    } finally {
      setLoadingLimit(null);
    }
  };

  return (
    <div className="page">
      <h2>Movie Details</h2>
      <div className="fetch-actions">
        {LIMITS.map((limit) => (
          <button
            key={limit}
            type="button"
            onClick={() => fetchMovies(limit)}
            disabled={loadingLimit !== null}
            className="fetch-button"
          >
            Pobierz pierwsze {limit}
          </button>
        ))}
      </div>
      <ul className="fetch-log">
        {logs.map((entry, index) => (
          <li key={`${entry}-${index}`}>{entry}</li>
        ))}
      </ul>
    </div>
  );
};

export default MovieDetails;
